@startuml classdiagram


 package api {
    package monetary {
        interface Product {
            + price(): double
        }      
    }
    package dietetic{
        Interface DieteticElement {
            + Kcalorie100g()
        }
    }
    package Restauration{
        Interface Food extends Product, DieteticElement{
         + weight() : double
         + colorie() : double<default>

        }
        Interface Base extends DieteticElement , Product{
           + hasUniquePrice :bool
       }
       Class Ingerdient implements Food {
            - weight:double
            + this(base:Base,weight:double)
            + calorie100g():double
            + weight():double
            + calorie(): double
            + price():double
            
       }
       Ingerdient *-> "~base 1" Base
     
       abstract class Recipe  extends Food implements ComposedFood {
            - name: string
            + this(name: string, ingerdienta: List<Ingredient>)
            + weight(): double
            + price(): double
            + Kcalorie() : double 
            + Kcalorie100g() : double 
        }
         
       Recipe *-> "ingredients *" Food
       Interface ComposedFood extends Food{
           add(base:Base,weight:double);
       }
       
       
    }
    
    package Burger {
        enum BurgerBase implements ComposedFood{
            BURGER, BARBECUE, BEARNAISE,BEEF,WHITEFISH,CHEDDAR,
            DEEPERIEDONIONS,TOMATO 
            + calorie100g():double
            + price():double
            + hasUniquePrice():bool
        }


        Class Burger extends Recipe  {
          this(name:stringm ingredients:List<Ingredient>)
     
        }

        Enum MenuSize{
            SMALL,MEIUM,BIG
            meatWeight() : double


        }

        Enum MenuType{
            MEAT_MENU,FISH_MENU,CHEESE_MENU
        }

        Class BurgerBuilder implements MenuSize,MenuType,Burger{
            ~name: string 
            order_name(name : string, type :MenuType):BurgerBuilder
            order_beef(name : string,size:MenuSize) : BurgerBuilder
            order_bish(name: string ,size :MenuSize) : BurgerBuilder
            with_barbecue_sauce():BurgerBuilder
            with_bearnaise_sauce():BurgerBuilder
            with_cheddar():BurgerBuilder
            with_onions():BurgerBuilder
            with_tomato():BurgerBuilder
            cook():ComposedFood
        


        }
        Class Burger {
            this(name:string)
        }
  
        
    }
    
}
package client {
    class App implements MenuType,BurgerBuilder,Food,MenuSize{
       static main(arg:string[3]):void
    }
}

 

@enduml
